--TERMEK tábla
--KONYV
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Minta', 1999, 999);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('But I Feel the Bright Eyes...', 1994, 3000);INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Girl', 1910, 666); INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Go By Go',1998, 777); INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ("I can't said the ant", 1961, 888); INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('I Like It Here', 1950, 3000); INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('I Like It Here Too', 1951, 1000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A mágia fénye', 1998, 2000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A mágia színe', 1999, 1999);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Egyenjogú rítusok', 1992, 3000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Mort, A Halál kisinasa', 1998, 4000);
--ZENE
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('At the Heart of Winter', 1999, 1000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Rubber Soul', 1965, 2000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Led Zeppelin IV', 1971, 1000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Paranoid', 1970, 1000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('13', 2013, 3000); 
--FILM
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A remény rabjai', 1994, 2000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A keresztapa', 1972, 2000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A keresztapa II', 1974, 2222);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A sötét lovag', 2008, 3000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Schindler listája', 2004, 5000); 
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Ponyvaregény', 2004, 5000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A Gyűrűk Ura: A gyűrű szövetsége', 2001, 2000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('A Birodalom visszavág', 1980, 2000);
INSERT INTO SYSTEM.TERMEK (CIM, KIADAS_EVE, AR) VALUES ('Hetedik', 1995, 2000);  
--KONYV tábla
INSERT INTO SYSTEM.KONYV (TERMEK_ID) VALUES (1);
INSERT INTO SYSTEM.KONYV (TERMEK_ID) VALUES (2);
INSERT INTO SYSTEM.KONYV (TERMEK_ID) VALUES (3);
INSERT INTO SYSTEM.KONYV (TERMEK_ID) VALUES (4);
INSERT INTO SYSTEM.KONYV (TERMEK_ID) VALUES (5);
INSERT INTO SYSTEM.KONYV (TERMEK_ID) VALUES (6);
--E-BOOK tábla
INSERT INTO SYSTEM.E_BOOK (TERMEK_ID) VALUES (7);
INSERT INTO SYSTEM.E_BOOK (TERMEK_ID) VALUES (8);
INSERT INTO SYSTEM.E_BOOK (TERMEK_ID) VALUES (9);
INSERT INTO SYSTEM.E_BOOK (TERMEK_ID) VALUES (10);
INSERT INTO SYSTEM.E_BOOK (TERMEK_ID) VALUES (11);
--ZENE tábla
INSERT INTO SYSTEM.ZENE (TERMEK_ID, EGYUTTES_NEVE) VALUES (12, 'Immortal');
INSERT INTO SYSTEM.ZENE (TERMEK_ID, EGYUTTES_NEVE) VALUES (13, 'The Beatles');
INSERT INTO SYSTEM.ZENE (TERMEK_ID, EGYUTTES_NEVE) VALUES (14, 'Led Zeppelin');
INSERT INTO SYSTEM.ZENE (TERMEK_ID, EGYUTTES_NEVE) VALUES (15, 'Black Sabbath');
INSERT INTO SYSTEM.ZENE (TERMEK_ID, EGYUTTES_NEVE) VALUES (16, 'Black Sabbath');
--FILM tábla
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (17, 'Frank Darabont');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (18, 'Francis Ford Coppola');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (19, 'Francis Ford Coppola');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (20, 'Christopher Nolan');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (21, 'Steven Spielberg');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (22, 'Quentin Tarantino');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (23, 'Peter Jackson');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (24, 'Irvin Kershner');
INSERT INTO SYSTEM.FILM (TERMEK_ID, RENDEZO) VALUES (25, 'David Fincher');
--KONYV_SZERZO tábla
INSERT INTO SYSTEM.KONYV_SZERZO (KONYV_TERMEK_ID, SZERZO) VALUES (1, 'Mintaszerző');
INSERT INTO SYSTEM.KONYV_SZERZO (KONYV_TERMEK_ID, SZERZO) VALUES (2, 'Bill Crider');
INSERT INTO SYSTEM.KONYV_SZERZO (KONYV_TERMEK_ID, SZERZO) VALUES (3, 'O. Henry');
INSERT INTO SYSTEM.KONYV_SZERZO (KONYV_TERMEK_ID, SZERZO) VALUES (4, 'Jon A. Jackson');
INSERT INTO SYSTEM.KONYV_SZERZO (KONYV_TERMEK_ID, SZERZO) VALUES (5, 'Polly Cameron');
INSERT INTO SYSTEM.KONYV_SZERZO (KONYV_TERMEK_ID, SZERZO) VALUES (6, 'Carl Zuckmayer');
/--E_BOOK_SZERZO tábla
INSERT INTO SYSTEM.E_BOOK_SZERZO (E_BOOK_TERMEK_ID, SZERZO) VALUES (7, 'Carl Zuckmayer');
INSERT INTO SYSTEM.E_BOOK_SZERZO (E_BOOK_TERMEK_ID, SZERZO) VALUES (8, 'Terry Pratchett');
INSERT INTO SYSTEM.E_BOOK_SZERZO (E_BOOK_TERMEK_ID, SZERZO) VALUES (9, 'Terry Pratchett');
INSERT INTO SYSTEM.E_BOOK_SZERZO (E_BOOK_TERMEK_ID, SZERZO) VALUES (10, 'Terry Pratchett');
INSERT INTO SYSTEM.E_BOOK_SZERZO (E_BOOK_TERMEK_ID, SZERZO) VALUES (11, 'Terry Pratchett');
--MUFAJ tábla
--KONYV
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (1, 'minta');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (2, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (3, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (4, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (5, 'humor');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (5, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (6, 'sci-fi');
--E_BOOK
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (7, 'humor');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (8, 'humor');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (8, 'sci-fi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (9, 'humor');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (9, 'sci-fi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (10, 'humor');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (10, 'sci-fi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (11, 'humor');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (11, 'sci-fi');
--ZENE
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (12, 'black metal');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (13, 'psychedelic rock');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (14, 'psychedelic rock');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (15, 'doom metal');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (16, 'doom metal');
--FILM
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (17, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (17, 'bűnügyi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (18, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (18, 'bűnügyi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (19, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (19, 'bűnügyi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (20, 'akció');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (20, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (20, 'thriller');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (21, 'történelem');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (21, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (22, 'bűnügyi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (22, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (22, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (23, 'kaland');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (23, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (23, 'fantasy');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (24, 'kaland');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (24, 'akció');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (24, 'sci-fi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (25, 'bűnügyi');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (25, 'dráma');
INSERT INTO SYSTEM.MUFAJ (TERMEK_ID, MUFAJ) VALUES (25, 'thriller');
--LAKCIM tábla
INSERT INTO SYSTEM.LAKCIM (IRSZAM, HAZSZAM, VAROS, UTCA) VALUES (6725, 88, 'Szeged', 'Tisza Lajos krt.');
INSERT INTO SYSTEM.LAKCIM (IRSZAM, HAZSZAM, VAROS, UTCA) VALUES (6725, 24, 'Szeged', 'Tisza Lajos krt.');
INSERT INTO SYSTEM.LAKCIM (IRSZAM, HAZSZAM, VAROS, UTCA) VALUES (6725, 10, 'Szeged', 'Tisza Lajos krt.');
INSERT INTO SYSTEM.LAKCIM (IRSZAM, HAZSZAM, VAROS, UTCA) VALUES (6725, 14, 'Szeged', 'Tisza Lajos krt.');
--FELHASZNALO tábla
INSERT INTO SYSTEM.FELHASZNALO (LAKCIM_ID, NEV, TIPUS, JELSZO) VALUES (null, 'admin', 'admin', 'admin');
INSERT INTO SYSTEM.FELHASZNALO (LAKCIM_ID, NEV, TIPUS, JELSZO) VALUES (null, 'admin1', 'admin', 'admin1');
INSERT INTO SYSTEM.FELHASZNALO (LAKCIM_ID, NEV, TIPUS, JELSZO) VALUES (1, 'andrea123', 'felhasznalo', '123');
INSERT INTO SYSTEM.FELHASZNALO (LAKCIM_ID, NEV, TIPUS, JELSZO) VALUES (2, 'bela123', 'felhasznalo', '123');
INSERT INTO SYSTEM.FELHASZNALO (LAKCIM_ID, NEV, TIPUS, JELSZO) VALUES (3, 'cecil123', 'felhasznalo', '123');
INSERT INTO SYSTEM.FELHASZNALO (LAKCIM_ID, NEV, TIPUS, JELSZO) VALUES (4, 'david123', 'felhasznalo', '123');
--BOLT tábla
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (1, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (2, 'Libri', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (3, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (4, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (5, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (6, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (7, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (8, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (9, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (10, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (11, 'Libri', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (18, 'Libri', 2);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (12, 'Libri', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (12, 'Musik', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (13, 'Musik', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (14, 'Musik', 2);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (15, 'Musik', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (16, 'Musik', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (17, 'Filmtár', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (18, 'Filmtár', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (19, 'Filmtár', 2);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (20, 'Filmtár', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (21, 'Filmtár', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (22, 'Filmtár', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (23, 'Filmtár', 2);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (25, 'Filmtár', 4);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (21, 'Vegyesbolt', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (1, 'Vegyesbolt', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (5, 'Vegyesbolt', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (17, 'Vegyesbolt', 3);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (10, 'Vegyesbolt', 2);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (15, 'Vegyesbolt', 1);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (12, 'Vegyesbolt', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (12, 'Vegyesbolt', 5);
INSERT INTO SYSTEM.BOLT (TERMEK_ID, NEV, DARABSZAM) VALUES (24, 'Vegyesbolt', 1);